### ISSUE TITLE
Decouple Queue Providers from qpush-bundle

### ISSUE THREAD

**Issue by jeremygiberson** [uecode/qpush-bundle#101]
In general, I would greatly welcome an abstraction layer for multiple queues and this bundle does just that [in addition to some other stuff]. I'd really like to see the queue Provider interface and the provider adapters for ironmq, aws, file, etc to be pulled out into a separate library(s).

**Comment by kmfk** [comment]
Im definitely not opposed to this - but not sure if I have the bandwidth to look at doing it right now. Not sure if there is more interest from the community?

**Comment by jeremygiberson** [comment]
I'm happy to help with this. I'm willing to pull the code out into its own library and make a PR that requires the new package. I'll need you to fork it and submit it to packagist though so it stays under your vendor name. Once its available, I'll submit a pull request against qpush-bundle that drops the classes and requires the libraries.
