### ISSUE TITLE
Error when running receive command.

### ISSUE THREAD

**Issue by vamsiikrishna** [uecode/qpush-bundle#126]
Hi,
When I run
``` php app/console uecode:qpush:receive my_queue_name```

 I am getting                                                             
  ```[Symfony\Component\Debug\Exception\ContextErrorException]  
  Warning: Invalid argument supplied for foreach()

**Comment by kmfk** [comment]
@vamsiikrishna What queue provider are you using?  The receive method should, ideally, always be returning an array, empty or otherwise.  Curious how this is happening.

**Comment by tiagobrito** [comment]
I'm also having this. I'm using AWS SQS provider.

**Comment by tiagobrito** [comment]
@vamsiikrishna I think you are receiving from sync provider.
@kmfk Sync provider implementation isn't returning an array:

```php
public function receive(array $options = []) {}
```
