### ISSUE TITLE
AWS version incompatability

### ISSUE THREAD

**Issue by aequasi** [uecode/qpush-bundle#59]
You should mark that the aws-sdk dependency only works for version 2. Version 3 wont work.

`>=2.0.0,<3.0.0` or something

**Comment by xabbuh** [comment]
`~2.5` will not install `3.*`.

**Comment by aequasi** [comment]
Updated the original post, issue still stands however

**Comment by chriwup** [comment]
I have added support for aws sdk v3 in pull request #81, still compatibile with v2. If it get merged this issue could be closed.
