### ISSUE TITLE
[BUG] Full Class Name is required

### ISSUE THREAD

**Issue by pmartelletti** [uecode/qpush-bundle#70]
In this line:

https://github.com/uecode/qpush-bundle/blob/f4434eda785da69ce16663c0895507d8cf20ca86/src/DependencyInjection/UecodeQPushExtension.php#L174

I need to changed the line to:

```
if (!class_exists('IronMQ\IronMQ')) {
```

because if not the class would not be find.

**Comment by xabbuh** [comment]
@pmartelletti Is this the same issue as described in https://github.com/uecode/qpush-bundle/pull/69#issuecomment-86628114?

**Comment by pmartelletti** [comment]
@xabbuh indeed! My bad! I'll close it. :smile:
