### ISSUE TITLE
Securing incoming routes?

### ISSUE THREAD

**Issue by rcwsr** [uecode/qpush-bundle#72]
It looks like the bundle doesn't have a way of verifying that it is _actually_ SQS or IronMQ calling my application. Could you recommend a way of accomplishing this?

**Comment by kmfk** [comment]
@robcaw - This is a good feature request.  My thought would be allowing you to set a random token in your configuration that would be automatically applied to any subscriber endpoints you configure, so we would check against that token for all requests.

Would that work for you?

**Comment by robcaw** [comment]
That would be perfect. I noticed that's what IronMQ recommends doing in their documentation, would the same work for SQS?

**Comment by jeskew** [comment]
@robcaw  The AWS SDK includes an [message verifier](https://github.com/aws/aws-sdk-php/blob/2.8/src/Aws/Sns/MessageValidator/MessageValidator.php) for SNS that should suffice. 

@kmfk Have you already started working on this feature?

**Comment by hubgit** [comment]
I was able to work around this by setting `uecode_qpush.request_listener.class` to a new class that extends the existing `RequestListener` and performs the message validation as a pre-processing step:

```php
<?php

namespace Acme\Bundle\EventListener;

use Aws\Sns\Message;
use Aws\Sns\MessageValidator;
use Symfony\Component\HttpKernel\Event\GetResponseEvent;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\HttpKernel\HttpKernel;
use Uecode\Bundle\QPushBundle\EventListener\RequestListener as QPushRequestListener;

class RequestListener extends QPushRequestListener
{
    /**
     * Extend the qpush kernel request listener, adding SNS message verification
     *
     * @param GetResponseEvent $event
     */
    public function onKernelRequest(GetResponseEvent $event)
    {
        if (HttpKernel::MASTER_REQUEST !== $event->getRequestType()) {
            return;
        }

        if ($event->getRequest()->headers->has('x-amz-sns-message-type')) {
            try {
                 $message = Message::fromRawPostData();
                 $validator = new MessageValidator();
                 $validator->validate($message);
            } catch (\Exception $e) {
                throw new BadRequestHttpException();
            }

            parent::onKernelRequest($event);
        }
    }
}
```
