### ISSUE TITLE
Make it compatible with Symfony 3.0

### ISSUE THREAD

**Issue by francoispluchino** [uecode/qpush-bundle#84]
Is it planned to make it compatible this Bundle with Symfony 3.0?

**Comment by aequasi** [comment]
Yes! It may just be as easy as allowing the 3.0 version, if you'd like to try



—
Aaron Scherer
http://bldr.io/

**Comment by francoispluchino** [comment]
It's done :).

**Comment by kmfk** [comment]
Merged - will bump a new tag once other PRs are cleaned up.

**Comment by francoispluchino** [comment]
Ok! Thanks.
