### ISSUE TITLE
No longer working with IronMQ v3 API

### ISSUE THREAD

**Issue by petemcfarlane** [uecode/qpush-bundle#91]
I think there may be some changes to the IronMQ API which make this provider no longer work properly, for example, when receiving messages there is no `timeout` or `push_status` property on a message, but there is a `reservation_id`. 

[Response body of a message](http://dev.iron.io/mq/3/reference/api/#reserve-messages)

That `reservation_id` is also [required for deleting messages](http://dev.iron.io/mq/3/reference/api/#delete-message) after they have been handled, so currently no message can be deleted!

**Comment by kmfk** [comment]
Looks like this just got missed due to a small fix on the PR that went unnoticed.  Merged this in - closing out the issue.
