### ISSUE TITLE
Support for AWS PHP SDK v3

### ISSUE THREAD

**Issue by araines** [uecode/qpush-bundle#99]
The latest version of the AWS SDK is v3, it would be great to support it rather than the current v2.

**Comment by francoispluchino** [comment]
It's already the case, I use this bundle with the last version of the AWS SDK:
```json
{
  "require": {
    "aws/aws-sdk-php": "3.18.*"
  }
}
```

**Comment by araines** [comment]
Ah great - I guess its just a case of updating the docs in that case :)  Good to know, it means I can start having a play with this library.

**Comment by kmfk** [comment]
@araines noted in the [docs](http://qpush-bundle.readthedocs.io/en/latest/aws-provider.html) now.  thanks!
